version: "3"
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:6.0.1
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
    - "2181:2181"
    logging:
      driver: none
 
  kafka-broker:
    image: confluentinc/cp-kafka:6.0.1
    ports:
    - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_LISTENERS: "PUBLIC://0.0.0.0:9092,INTERNAL://0.0.0.0:19092"
      KAFKA_ADVERTISED_LISTENERS: "PUBLIC://localhost:9092,INTERNAL://kafka-broker:19092"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "PUBLIC:PLAINTEXT,INTERNAL:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: "INTERNAL"
      KAFKA_NUM_PARTITIONS: 1
      KAFKA_DEFAULT_REPLICATION_FACTOR: 1
      KAFKA_OFFSETS_TOPIC_NUM_PARTITIONS: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_DELETE_TOPIC_ENABLE: "true"
      KAFKA_CONFLUENT_SUPPORT_METRICS_ENABLE: "false"
      KAFKA_LOG4J_ROOT_LOGLEVEL: "INFO"
    depends_on:
    - zookeeper
    logging:
      driver: none

  jobmanager:
    build:
      context: .
      dockerfile: Dockerfile.flink
    environment:
      ROLE: master
      MASTER_HOST: jobmanager
    #command:
    #  - "--fromSavepoint"
    #  - "/tmp/shopping.state"
    #volumes:
    #  - "/tmp/shopping.state:/tmp/shopping.state"
    #  - "../bootstrap-example/protocols/build/libs/protocols.jar:/opt/flink/lib/protocols.jar"
    expose:
    - "6123"
    ports:
    - "8081:8081"
    links:
    - "kafka-broker:kafka-broker"
    depends_on:
    - kafka-broker
    logging:
      driver: none

  taskmanager:
    build:
      context: .
      dockerfile: Dockerfile.flink
    environment:
      ROLE: worker
      MASTER_HOST: jobmanager
    expose:
    - "6121"
    - "6122"
    links:
    - "jobmanager:jobmanager"
    - "kafka-broker:kafka-broker"
    depends_on:
    - jobmanager
    - kafka-broker

  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    expose:
    - "8000"
